name: Auto Update average.json

on:
  schedule:
    - cron: '0 */2 * * *'  # 2시간마다
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Playwright
      run: |
        pip install playwright
        playwright install chromium

    - name: Run update script
      run: python update_average.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add average.json
        git commit -m "자동 갱신: average.json" || exit 0
        git push
